# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/eppie/pixelShuffle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/eppie/pixelShuffle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/eppie/pixelShuffle/CMakeFiles /Users/eppie/pixelShuffle//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/eppie/pixelShuffle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pngLAB

# Build rule for target.
pngLAB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pngLAB
.PHONY : pngLAB

# fast build rule for target.
pngLAB/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB.dir/build.make CMakeFiles/pngLAB.dir/build
.PHONY : pngLAB/fast

#=============================================================================
# Target rules for targets named pngLAB_clean

# Build rule for target.
pngLAB_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pngLAB_clean
.PHONY : pngLAB_clean

# fast build rule for target.
pngLAB_clean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_clean.dir/build.make CMakeFiles/pngLAB_clean.dir/build
.PHONY : pngLAB_clean/fast

#=============================================================================
# Target rules for targets named pngLAB_bench_core

# Build rule for target.
pngLAB_bench_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pngLAB_bench_core
.PHONY : pngLAB_bench_core

# fast build rule for target.
pngLAB_bench_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_bench_core.dir/build.make CMakeFiles/pngLAB_bench_core.dir/build
.PHONY : pngLAB_bench_core/fast

#=============================================================================
# Target rules for targets named pngLAB_bench_e2e

# Build rule for target.
pngLAB_bench_e2e: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pngLAB_bench_e2e
.PHONY : pngLAB_bench_e2e

# fast build rule for target.
pngLAB_bench_e2e/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_bench_e2e.dir/build.make CMakeFiles/pngLAB_bench_e2e.dir/build
.PHONY : pngLAB_bench_e2e/fast

#=============================================================================
# Target rules for targets named shouldSwap_ab_harness

# Build rule for target.
shouldSwap_ab_harness: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shouldSwap_ab_harness
.PHONY : shouldSwap_ab_harness

# fast build rule for target.
shouldSwap_ab_harness/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shouldSwap_ab_harness.dir/build.make CMakeFiles/shouldSwap_ab_harness.dir/build
.PHONY : shouldSwap_ab_harness/fast

#=============================================================================
# Target rules for targets named hungarian

# Build rule for target.
hungarian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hungarian
.PHONY : hungarian

# fast build rule for target.
hungarian/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hungarian.dir/build.make CMakeFiles/hungarian.dir/build
.PHONY : hungarian/fast

#=============================================================================
# Target rules for targets named asm

# Build rule for target.
asm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asm
.PHONY : asm

# fast build rule for target.
asm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/build
.PHONY : asm/fast

#=============================================================================
# Target rules for targets named profile

# Build rule for target.
profile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 profile
.PHONY : profile

# fast build rule for target.
profile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile.dir/build.make CMakeFiles/profile.dir/build
.PHONY : profile/fast

hungarian.o: hungarian.cpp.o
.PHONY : hungarian.o

# target to build an object file
hungarian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hungarian.dir/build.make CMakeFiles/hungarian.dir/hungarian.cpp.o
.PHONY : hungarian.cpp.o

hungarian.i: hungarian.cpp.i
.PHONY : hungarian.i

# target to preprocess a source file
hungarian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hungarian.dir/build.make CMakeFiles/hungarian.dir/hungarian.cpp.i
.PHONY : hungarian.cpp.i

hungarian.s: hungarian.cpp.s
.PHONY : hungarian.s

# target to generate assembly for a file
hungarian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hungarian.dir/build.make CMakeFiles/hungarian.dir/hungarian.cpp.s
.PHONY : hungarian.cpp.s

pngLAB.o: pngLAB.cpp.o
.PHONY : pngLAB.o

# target to build an object file
pngLAB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB.dir/build.make CMakeFiles/pngLAB.dir/pngLAB.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_bench_core.dir/build.make CMakeFiles/pngLAB_bench_core.dir/pngLAB.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_bench_e2e.dir/build.make CMakeFiles/pngLAB_bench_e2e.dir/pngLAB.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shouldSwap_ab_harness.dir/build.make CMakeFiles/shouldSwap_ab_harness.dir/pngLAB.cpp.o
.PHONY : pngLAB.cpp.o

pngLAB.i: pngLAB.cpp.i
.PHONY : pngLAB.i

# target to preprocess a source file
pngLAB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB.dir/build.make CMakeFiles/pngLAB.dir/pngLAB.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_bench_core.dir/build.make CMakeFiles/pngLAB_bench_core.dir/pngLAB.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_bench_e2e.dir/build.make CMakeFiles/pngLAB_bench_e2e.dir/pngLAB.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shouldSwap_ab_harness.dir/build.make CMakeFiles/shouldSwap_ab_harness.dir/pngLAB.cpp.i
.PHONY : pngLAB.cpp.i

pngLAB.s: pngLAB.cpp.s
.PHONY : pngLAB.s

# target to generate assembly for a file
pngLAB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB.dir/build.make CMakeFiles/pngLAB.dir/pngLAB.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_bench_core.dir/build.make CMakeFiles/pngLAB_bench_core.dir/pngLAB.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_bench_e2e.dir/build.make CMakeFiles/pngLAB_bench_e2e.dir/pngLAB.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shouldSwap_ab_harness.dir/build.make CMakeFiles/shouldSwap_ab_harness.dir/pngLAB.cpp.s
.PHONY : pngLAB.cpp.s

pngLAB_clean.o: pngLAB_clean.cpp.o
.PHONY : pngLAB_clean.o

# target to build an object file
pngLAB_clean.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_clean.dir/build.make CMakeFiles/pngLAB_clean.dir/pngLAB_clean.cpp.o
.PHONY : pngLAB_clean.cpp.o

pngLAB_clean.i: pngLAB_clean.cpp.i
.PHONY : pngLAB_clean.i

# target to preprocess a source file
pngLAB_clean.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_clean.dir/build.make CMakeFiles/pngLAB_clean.dir/pngLAB_clean.cpp.i
.PHONY : pngLAB_clean.cpp.i

pngLAB_clean.s: pngLAB_clean.cpp.s
.PHONY : pngLAB_clean.s

# target to generate assembly for a file
pngLAB_clean.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pngLAB_clean.dir/build.make CMakeFiles/pngLAB_clean.dir/pngLAB_clean.cpp.s
.PHONY : pngLAB_clean.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... asm"
	@echo "... profile"
	@echo "... hungarian"
	@echo "... pngLAB"
	@echo "... pngLAB_bench_core"
	@echo "... pngLAB_bench_e2e"
	@echo "... pngLAB_clean"
	@echo "... shouldSwap_ab_harness"
	@echo "... hungarian.o"
	@echo "... hungarian.i"
	@echo "... hungarian.s"
	@echo "... pngLAB.o"
	@echo "... pngLAB.i"
	@echo "... pngLAB.s"
	@echo "... pngLAB_clean.o"
	@echo "... pngLAB_clean.i"
	@echo "... pngLAB_clean.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

